### ISSUE TITLE
Issue regarding row limit

### ISSUE THREAD

**Issue by AnishArjun05** [SAP-samples/data-warehouse-cloud-connectors#6] opened 2023-01-18 12:38 UTC
Hello,

I have tried to import different datasets with different number of rows from Data Warehouse Cloud but it seems like there is a limit related to the size of the model that is being imported. 

By default the number of rows getting imported is 1000 and when we specify the number of rows, depending on the size of the model especially if the model has string values in it and if the model has more than 10000 rows, the number of rows are reduced considerably (in our case Model= 599999 rows and in Power BI= 1000). 
![The model with the 599999 rows](https://user-images.githubusercontent.com/122973158/213171776-c436f25b-fec3-459e-a914-a8895c758e07.png)
![Specifying the number of rows in the field](https://user-images.githubusercontent.com/122973158/213171793-19ad05b7-8926-42d5-aa27-a081915145a3.png)
![Data with 599999 rows ](https://user-images.githubusercontent.com/122973158/213171823-a83df686-3f7b-4d23-8248-ca20a094116b.png)

We tried to import data with only integer values and we were able to import up to 500000. We figured there might be an limitation with the size of the model being imported. 
![Imported data with only integers](https://user-images.githubusercontent.com/122973158/213171867-c0816b13-1b48-45ce-94a8-29a32e10c048.png)

Is this true or is there any workaround for this. We have attached Screenshots for your reference and to understand the issue better. And we have an active Premium Power BI account and we have a SAP Licensed DWC account.

Thank You in advance.

**Comment by OlafFischer** [comment] 2023-01-19 07:33
Hi AnishArjun05,
as first step, I would like to check the ODATA response of DWC when called directly - without PowerBI. If we observe your described behavior without PowerBI involved, the root cause is likely to be within DWC.

Could you replace the <..> with your concrete values and call the URL from your browser? 
https://<your-tenant>.hcs.cloud.sap/dwaas-core/odata/v4/consumption/relational/<space>/<view_name>/<view_name>

The call will return the full fact table of your view. Check the response with respect to the row-count (value property).
Depending on the result, add ?$top=xxx , where xxx is the count of records you like to fetch.

Looking forward to your results, Olaf

**Comment by AnishArjun05** [comment] 2023-01-24 12:01
Hi Olaf,
Sorry for the late reply. we tried to use the link you pasted the chat but we got an error that the page was not found. 

1) The tenant url must end before the .hcs.cloud.sap right

2) The <view name>/<view name> is the space name first and model technical name right? 

3)  {"@odata.context":"http://<tenant url>/dwaas-core/odata/v4/consumption/relational/<Space name>/<View Name>/$metadata","@odata.metadataEtag":"W/\"zQKwsstvVNK2KADSw6JGnP/gmSsPeRqnJ7FcDYukl7w=\"","value":[{"name":<View name>,"url":<View name>}]}

3rd point was the response we got from using the url that you have given in the previous comment, Can you explain how should we move forward.

**Comment by OlafFischer** [comment] 2023-01-24 14:47
Hi AnishArj,
I had a typo in the URL template:
https://< your-tenant >.hcs.cloud.sap/dwaas-core/odata/v4/consumption/relational/<space_name>/<view_name>/<view_name>.
Could you please try again?
Thanks, Olaf

**Comment by AnishArjun05** [comment] 2023-01-25 11:13
Hi Olaf,
The link is working now.
We tried to use the model without specifying the number of rows and it did not pull the exact number of rows present in DWC.
But the number of rows pulled was different for different models.

![Screenshot (97)](https://user-images.githubusercontent.com/122973158/214547499-6b065dce-e7ad-4a63-9d74-3b0f28fc8a92.png)


![Screenshot (98)](https://user-images.githubusercontent.com/122973158/214547486-4d11279e-d235-4e2f-a70c-d8e27696e588.png)


![Screenshot (99)](https://user-images.githubusercontent.com/122973158/214547513-2a5bb670-f35a-4af6-833c-76400d2f923f.png)

The different model which pulled all the data

![Screenshot (100)](https://user-images.githubusercontent.com/122973158/214548888-fe6fc063-87b2-4178-a9f1-62d45cf2f47b.png)

![Screenshot (101)](https://user-images.githubusercontent.com/122973158/214548931-a0943618-e9de-4b18-b683-d3ec75930c13.png)

**Comment by OlafFischer** [comment] 2023-01-31 16:55
Hi AnishArjun, 
this result points towards DWC - coming potentially with an internal default for the number of rows returned. You might want to try to overwrite this default with an explicit ?$top=10000 at the end of the URL. If this doesn't work, I would propose to contact your DWC support.

In addition, I would like to share some hints/updates when using PowerBi and OData:
- In the data preview, PowerBi adds always a $top=1000 to the requests. As a consequence, the preview shows at maximum 1000 rows of data.
- When refining the OData query (the button "Transform Data" on the data preview dialog), you can define a custom value for the top number of rows to the fetched. When this configuration is used, PowerBi will send your custom value back to DWC.
As a consequence, I have remove the option to select the number of rows from the parameter screen in the latest version.
Best regards, Olaf

**Comment by OlafFischer** [comment] 2023-01-31 17:11
Hi AnishArjun, could you please close the issue if you have no further questions? Thanks, Olaf

**Comment by AnishArjun05** [comment] 2023-02-03 13:12
Hi Olaf,

We did the whole process againg by redownloading the tweaked repository file to try out the suggestion you gave but it was throwing the following error.


![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/122973158/216611899-3fbc3ad0-f32e-4e2e-8c7b-b61b8390b2df.png)

**Comment by OlafFischer** [comment] 2023-02-05 20:53
Hi AnishArjun, 

As your current finding is new issue I have created a separate one:
https://github.com/SAP-samples/data-warehouse-cloud-connectors/issues/8 

With respect to the row limit: Your observed behaviour with different number of result rows goes along with the documentation. https://help.sap.com/docs/SAP_DATA_WAREHOUSE_CLOUD/c8a54ee704e94e15926551293243fd1d/811a5f0dc279492a9b87c8c8d7ba7181.html?locale=en-US&q=odata

Due to the implemented size limit (volume of the request) of the response, the number of rows will decrease when the rows size increases. 

An example that illustrates the behaviour:
- number of rows returned = 20MB / size of single row

Please note that the new version can't change or work-around this server side behaviour. There is no suggestion available to achieve your desired outcome, as the volume limitations overrides the number provided by the $top property.

Best regards, Olaf

**Closed** 2023-02-05 20:53 UTC
